apiVersion: v1
kind: Secret
metadata:
  name: pay-recorrenciagestao-api
  namespace: pay-ns1-d
type: Opaque
stringData:
  dbconfig_connectionstring: Server=CADOD-DBSQLW001\\SQLDSV1,2023;Database=DBPAYRECGES; User Id=usr_payrecges_app;Password=usr_payrecges_app;
  redis_sentinel: 'CADOH-SVCPJL001:26379,CADOH-SVCPJL002:26379,CADOH-SVCPJL003:26379'
  redis_cluster: 'CADOH-SVCPJL001:6379,CADOH-SVCPJL002:6379,CADOH-SVCPJL003:6379'
  redis_name: localhost
  redis_port: '6379'
  kafka_bootstrap_server: kafka-hmg-kafka-bootstrap.kfk-ns1-h.svc:9093
  kafka_usr: usr-pay-des
  kafka_usr_pass: jEyhrf6dQLjaDj3t51JWNUGka05ZDGVS
  EndpointAutorizacaoRecorrencia: https://rt-pay-recorrenciagestao-api-d-pay-ns1-d.apps.ops-hmg.crefisa.com.br/v1/pix-automatico/autorizacoes-recorrencia
  EndpointDadosUsuario: https://servicos-admin-api-h.crefisa.com.br:442/accounts
  EndpointPush: https://rt1-ctn-ns1-d.apps.ops-hmg.crefisa.com.br
