apiVersion: v1
kind: Secret
metadata:
  name: pay-recorrenciagestao-api
  namespace: pay-ns1-d
type: Opaque
stringData:
  dbconfig_connectionstring: >-
    Server=CADOD-DBSQLW001\SQLDSV1;Database=DBPAYRECGES;User Id=USR_PAY_RECGES_DEV;password=8pd64T5@;Trusted_Connection=SSPI;Encrypt=false;TrustServerCertificate=true;MultipleActiveResultSets=true;
  redis_sentinel: 'CADOH-SVCPJL001:26379,CADOH-SVCPJL002:26379,CADOH-SVCPJL003:26379'
  redis_cluster: 'CADOH-SVCPJL001:6379,CADOH-SVCPJL002:6379,CADOH-SVCPJL003:6379'
  redis_name: localhost
  redis_port: '6379'
  kafka_bootstrap_server: kafka-hmg-kafka-bootstrap.kfk-ns1-h.svc:9093
  kafka_usr: usr-pay-des
  kafka_usr_pass: jEyhrf6dQLjaDj3t51JWNUGka05ZDGVS
